version: "3.8"
services:
  anki-sync-server:
    image: myflow/anki-sync-server:23.10.1
    env_file: .env
    user: "${PUID}:${GUID}"
    volumes:
      - ./data:/.syncserver
    ports:
      - 80:8080
